/**
 *  Description     :   Constant class for the variable having same value used for one or more places in the apex classes. 
 *  Created By      :   Abhishek Tripathi 
 *  Created Date    :   9/11/2016   
 *  Version         :   V1.0     
 **/
public class Constant {
	
    //Constants to use org-wide classes
    public static final String REFINE = 'Refine';
    public static final String OBJECTIVE_SELLIN = 'Sell-In New Item';
    public static final String OBJECTIVE_ITEM_CONVERSION = 'Item Conversion';
    public static final String OBJECTIVE_SELL_IN_CORE_ITEMS = 'Sell-In Core Items (Not in Distribution)';
    public static final String OBJECTIVE_FIX = 'Fix the Mix';
    public static final String INITIATIVE_ASSORTMENT = 'Assortment / Distribution';
    public static final String STATUS_ACCEPTED = 'Accepted';
    public static final String STATUS_REJECTED = 'Rejected';
    public static final String STATUS_PENDING = 'Pending';
    public static final String STATUS_NOT_PROPOSED = 'Not-Proposed';
    public static final String STATUS_OTHER = 'Other';
    public static final String STATUS_COMPLETED = 'Completed';
    
    
    
    public static final String ISNATIONAL = 'isNational';
    public static final String ISLOCAL = 'isLocal';
    public static final String CUSTOMER_RECORD_TYPE_L5 = 'Customer - Sub Banner - L5';
    public static final String CUSTOMER_RECORD_TYPE_L4 = 'Customer - Banner - L4';
    public static final String STATUS_ALLOCATED = 'Allocated';
    public static final String INITIATIVE_DISPOSITION = 'Initiative Disposition';
    
    
    
    
    
    
    
}